<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete scholarship');

if(isset($_GET['Scholarship_id']))
{
    $Scholarship_id = urldecode($_GET['Scholarship_id']);
    require_once 'form_data_scholarship.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_scholarship.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/scholarship.php';
        $dbh_scholarship = new scholarship;

        $object_name = 'dbh_scholarship';
        require 'components/create_form_data.php';


        $dbh_scholarship->delete($arr_form_data);

        redirect("listview_scholarship.php?$query_string");
    }
}
require 'subclasses/scholarship_html.php';
$html = new scholarship_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('Scholarship_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();