<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit student');

if(isset($_GET['Student_id']))
{
    $Student_id = urldecode($_GET['Student_id']);
    require 'form_data_student.php';
    $orig_Student_id = $Student_id;
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/student.php';
    $dbh_student = new student;

    $object_name = 'dbh_student';
    require 'components/create_form_data.php';
    $arr_form_data['orig_Student_id'] = $_POST['orig_Student_id'];
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_student.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_student->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_student->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {

            $dbh_student->edit($arr_form_data);

            redirect("listview_student.php?$query_string");
        }
    }
}
require 'subclasses/student_html.php';
$html = new student_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('orig_Student_id');
$html->draw_controls('edit');

$html->draw_footer();